apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-and-kubernets
spec: 
  selector:
    matchLabels:
      app: webapp-and-kubernets
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-and-kubernets
    spec:
      containers:
      - name: webapp-and-kubernets
        image: okteto/webapp-and-kubernets:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wak1
spec:
  selector:
    app: webapp-and-kubernets
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer